import pyowm
owm = pyowm.OWM('f5f228ca75823de879e024d518f7a8cf')
observation = owm.weather_at_place("WR9 8BS")
w = observation.get_weather()
wind = w.get_wind()
temp = w.get_temperature('celsius')
tomorrow = pyowm.timeutils.tomorrow()
rain = w.get_rain()
humid = w.get_humidity()
sunrise = w.get_sunrise_time('iso')
sunset = w.get_sunset_time('iso')
print('Sunrise: '+sunrise)
print('Weather: ')
print(w)
print('Wind: '
print(wind)
print('Temperature, Celcius: '+temp)
print('Rain: '+rain)
print('Humidity: '+humid)
print('Sunset: '+sunset)
print('Tomorrows forecast: '+tomorrow)
